name: deploy-to-appian-demo

concurrency: appian-demo

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'uploads/packages/archive/**'

env:
  appian_api_key: ${{ secrets.APPIAN_API_KEY_DEMO }}
  appian_base_url: ${{ vars.APPIAN_BASE_URL_DEMO }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: appian-demo
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          zip_file_path=$(ls -Art uploads/packages/archive/*.zip | tail -n 1)
          zip_file_name=$(basename "${zip_file_path}")
          echo "$zip_file_path"
          echo "$zip_file_name"
          ins_res_1=$(curl -s -X POST -H "Appian-API-Key: ${appian_api_key}" \
            -F 'json="{
                \"packageFileName\": \"'"${zip_file_name}"'\"
              }"' \
            -F 'zipFile=@"'"${zip_file_path}"'"' \
            "${appian_base_url}deployment-management/v1/inspections")
          echo "$ins_res_1"
          ins_uuid=$(jq -n "${ins_res_1}" | jq '.uuid' | tr -d \")
          ins_url="${appian_base_url}deployment-management/v1/inspections/${ins_uuid}"
          echo "$ins_url"
          sleep 5
          ins_status="IN_PROGRESS"
          i=0
          while [ "$i" -lt 6 ]
          do
            ins_res_2=$(curl -s -X GET -H "Appian-API-Key: ${appian_api_key}" \
              "${ins_url}")
            echo "$ins_res_2"
            ins_status=$(jq -n "${ins_res_2}" | jq '.status' | tr -d \*)
            echo "$ins_status"
            
            if [ "${ins_status}" = "COMPLETED" ]; then
              break
            fi
            
            sleep 1
            i=$(($i + 1))
          done
          
          if [ "${ins_status}" = "COMPLETED" ]
          then
            curl -X POST -H "Appian-API-Key: ${appian_api_key}" \
            -F 'json="{
                \"name\": \"Deployment from GitHub CI/CD\",
                \"description\": \"Deployment from GitHub\",
                \"packageFileName\": \"'"${zip_file_name}"'\"
              }"' \
            -F 'randomKey1=@"'"${zip_file_path}"'"' \
            "${appian_base_url}deployment-management/v1/deployments"
          fi
