name: deploy-to-appian-demo

concurrency: appian-demo

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'uploads/packages/archive/**'

env:
  appian_api_key: ${{ secrets.APPIAN_API_KEY_DEMO }}
  appian_base_url: ${{ vars.APPIAN_BASE_URL_DEMO }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: appian-demo
    steps:
      - uses: actions/checkout@v3
      - name: inspect
        run: |
          zip_file_path=$(ls -Art uploads/packages/archive/*.zip | tail -n 1)
          zip_file_name=$(basename "${zip_file_path}")
          echo "$zip_file_path"
          echo "$zip_file_name"
          curl -s -X POST -H "Appian-API-Key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDU4ZjA1MS0xZTM1LTRiNGItODRiMy1lNGI2ODFmZjU1NWQifQ.mmmqwV3LPLIq7qgxendrkMe_7JtoyexR982QOHxGYLE" \
            -F 'json="{
                \"packageFileName\": \"Chenghua Sandbox.zip\"
              }"' \
            -F 'zipFile=@"uploads/packages/archive/Chenghua Sandbox.zip"' \
            "${appian_base_url}deployment-management/v1/inspections"
