name: extract a zip file
on:
  push:
    branches:
      - 'update'
    paths:
      - 'uploads/packages/*.zip'  
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unzip
        run: |
          rm -rf app
          filename=$(basename -s .zip uploads/packages/*.zip)
          mkdir app
          unzip uploads/packages/*.zip -d app
          mv uploads/packages/*.zip uploads/packages/archive/$(date +%F-%H:%M).zip

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "unzipped by github action"
          git push origin update
