name: extract a zip file
on:
  push:
    paths:
      - 'uploads/packages/*.zip'  
jobs:
  unzip:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2 
      - name: unzip
        run: |
          rm -rf app
          filename=$(basename -s .zip uploads/packages/*.zip)
          unzip uploads/packages/*.zip
          mv uploads/packages/*.zip uploads/packages/archive/$filename_$(date +%F-%H:%M).zip
          
          git config user.name chenghuazhangnxwavegmail
          git config user.email chenghuazhang.nxwave@gmail.com
          git add .
          git commit -m "unzip"
          git push origin main
