name: extract a zip file
on:
  push:
    branches:
      - 'update'
    paths:
      - 'uploads/packages/*.zip'  
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unzip
        run: |
          file_name=$(date +%F-%H:%M)
          echo "${filename}"
          mkdir -p app
          unzip -o uploads/packages/*.zip -d app
          mv uploads/packages/*.zip "uploads/packages/archive/${file_name}.zip"
          
          if [ -f uploads/packages/*.properties ]; then
           mv uploads/packages/*.properties "uploads/packages/archive/${file_name}.properties"
          fi
          
          if [ -f uploads/packages/*.sql ]; then
           mv uploads/packages/*.sql "uploads/packages/archive/${file_name}.sql"
          fi

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "unzipped by github action"
          git push origin update
